server:
  port: 9094
spring:
  application:
    name: JRTP-DataCollect_API-05
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Tara
    url: jdbc:mysql://localhost:3306/userdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
